#!/bin/sh

# kano-launcher
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# A simple script to launch Kano projects
# Usage: kano-launcher cmd [preset]

# Make sure there are no other projects running at the same time
killall -q python
killall -q minecraft-pi
killall -q make-music
killall -q make-video
killall -q make-snake

if [ -z "$1" ]; then
    exit 1
fi

eval "$1 &"

# Apply window presets
case "$2" in
    make-video)
        kano-window-tool -t "Make Video" -dno -w0.8 -h0.6 -c -f ;;
    make-snake)
        kano-window-tool -t "Make Snake" -dno -m -f ;;
    extras)
        kano-window-tool -t "extras" -c -f ;;
    feedback)
        kano-window-tool -t "Kano Feedback" -dno -c -f ;;
    settings)
        kano-window-tool -t "Kano-Settings" -dno -c -f ;;
esac

exit 0
