#!/usr/bin/python

# kano-launcher
#
# Copyright (C) 2013 Kano Computing Ltd.
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

import sys
import os

if __name__ == '__main__':

    # Check for the correct number of parameters
    if len(sys.argv) == 2:
        # Launch the app requested
        cmdline = sys.argv[1]
        rc = os.system(cmdline)
        sys.exit(rc)
    else:
        # Not the correct number of parameters, return error code 1
        sys.exit(1)
