#!/bin/sh

# make-common
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# Common functions for all scripts that start Kanux desktop icons
#

lockfile=/tmp/kano-launcher.lock

cleanup() {
    if [ -f $lockfile ]; then
        rm $lockfile
    fi
}
trap cleanup EXIT

is_app_running()
{
    # usage: mywid=""; is_app_running "mywndow" mywid
    # retuns 1 if running or 0 if not running, wid in $2
    wdata=`xwininfo -root -tree | grep "$1"`
    rc=$?
    if [ $rc -eq 0 ]; then
        wid=`echo $wdata | awk '{print $1}'`
        eval "$2=\"$wid\""
        return 1
    else
        return 0
    fi
}

kill_apps()
{
    # Close all other opened projects if any
    killall -q python
    killall -q minecraft-pi
    killall -q midori
    killall -q make-music
    killall -q make-video
    killall -q make-snake
}

protect_reentrancy()
{
    # if we are running, give focus and exit
    if [ -f $lockfile ]; then
	echo "$APPNAME2 is starting."
	exit 0
    else
	touch $lockfile
    fi
}