#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

TMP_FILE=/tmp/kano-toolset_conf

case "$1" in
    configure)

        # Create custom sudoers file
        echo 'Defaults env_keep += "KLOG_FORCE_FLUSH NO_AT_BRIDGE"' > $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-launcher" >> $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/is_internet" >> $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/sbin/ifplugstatus" >> $TMP_FILE

        # FIXME: Needed by new shutdown dialog, will eventually fix to non-sudo alternative
        echo "%sudo   ALL=(root) NOPASSWD: /bin/loginctl" >> $TMP_FILE

        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_FILE
        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE
        # Move the file to the sudoers directory
        mv $TMP_FILE /etc/sudoers.d/

        # Configure kano.logging
        if [ ! -f /etc/kano-logs.conf ]; then
            cat >/etc/kano-logs.conf <<EOF
log_level: error
output_level: none
EOF
        fi

	# kano-launcher is setuid root to allow use of CLONE_NEWUTS
	chmod u+s /usr/bin/kano-launcher

        # On jessie, Chromium is started as "chromium-browser" binary.
        which chromium > /dev/null
        if [ "$?" != "0" ]; then
            # Chromium binary is not in the path, create a symlink.
            # If is not yet installed, the symlink will
            # be resolved automatically when it does.
            ln -sf /usr/bin/chromium-browser /usr/bin/chromium
        fi

        ;;
esac

#DEBHELPER#

exit 0
