#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

TMP_FILE=/tmp/kano-toolset_conf

case "$1" in
    configure)

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-launcher" > $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/is_internet" >> $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/sbin/ifplugstatus" >> $TMP_FILE

        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_FILE
        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE
        # Move the file to the sudoers directory
        mv $TMP_FILE /etc/sudoers.d/

        # Configure kano.logging
        if [ ! -f /etc/kano-logs.conf ]; then
            cat >/etc/kano-logs.conf <<EOF
log_level: error
debug_level: none
EOF
        fi

        ;;
esac

#DEBHELPER#

exit 0
