#!/bin/bash

# kano-ifplugd
#
# Copyright (C) 2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# This script is called when network DHCP events occur
# It is called from /etc/udhcpc/kano.script (Kano Toolset packge)
# and sends the RaspberryPI CPU Serial Number to Kano. It runs as the superuser.
#
# Monitors the link status of the Internet through an external regular file
#
# Listens for DOWN events only, if the Internet is down, puts a mark in the external file.
# UP events are recorded from the kano-network-hook, because they have a much higher latency.
#

# file that external applications can monitor for internet availability triggers
monitor_file="/var/opt/internet_monitor"

if [ "$2" == "down" ]; then

    # We are testing internet connectivity now for if we are in multihomed mode (eth and wlan)
    is_internet
    if [ "$?" != "0" ]; then
	echo -e "internet: down\n" > $monitor_file
    fi
fi

exit 0
